### ISSUE TITLE
Toothpick is not compatible with AutoFactory

### ISSUE THREAD

**Issue by AleksanderMielczarek** [stephanenicolas/toothpick#187] opened 2017-01-08 14:06 UTC
Hi,

I'm getting familiar with Tootpick but I've encountered a problem using it with AutoFactory. Somehow generated factory is not valid. 

Sample project is on my repo: https://github.com/AleksanderMielczarek/ToothpickAutoFactoryIssue

**Error:**

```
error: Field com.github.aleksandermielczarek.toothpickautofactoryissue.MainActivity#itemFactory is not a valid ItemFactory.
    protected ItemFactory itemFactory;
```

**Activity:**

```java
public class MainActivity extends AppCompatActivity {

    @Inject
    protected ItemFactory itemFactory;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        Scope scope = Toothpick.openScope(this);
        super.onCreate(savedInstanceState);
        Toothpick.inject(this, scope);
    }

    @Override
    protected void onDestroy() {
        Toothpick.closeScope(this);
        super.onDestroy();
    }
}
```

**Item:**

```java
@AutoFactory
public class Item {
}
```

**Gradle:**

```groovy
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.github.aleksandermielczarek.toothpickautofactoryissue"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    provided 'com.google.auto.factory:auto-factory:1.0-beta3'
    apt 'com.google.auto.factory:auto-factory:1.0-beta3'
    compile 'com.github.stephanenicolas.toothpick:toothpick-runtime:1.0.3'
    apt 'com.github.stephanenicolas.toothpick:toothpick-compiler:1.0.3'
}
```

Best regards
Aleksander Mielczarek

**Comment by stephanenicolas** [comment] 2017-01-08 19:09
We never used `AutoFactory`. I am not sure we have the resources and the
interest to dig this issue. But we would be happy to get a PR merged if you
can fix the issue.

2017-01-08 6:06 GMT-08:00 Aleksander Mielczarek <notifications@github.com>:

**Comment by stephanenicolas** [comment] 2017-01-10 17:56
@AleksanderMielczarek if you add:

```groovy
    provided 'org.glassfish:javax.annotation:3.0.1'
```

to your `build.gradle`, and remove TP, then the build is working.

But, if you re-enable TP annotation processor, then it still fails.

This looks much more like a AutoFactory issue. There are no clear instructions for gradle, I don't see anything we can do. We close the issue.

**Comment by dlemures** [comment] 2017-01-10 17:57
@AleksanderMielczarek I have tried the example project removing Toothpick and it still fails.

It complains about: 
> import javax.annotation.Generated;

Could you make it work without TP and recheck so we are sure that the problem is coming from there?

**Comment by AleksanderMielczarek** [comment] 2017-01-10 18:58
@stephanenicolas Gradle instruction for AutoValue: http://ryanharter.com/blog/2016/04/08/autovalue-deep-dive/.
AutoFactory is generating following code, which is compatible with JSR-330. Dagger 2 can inject generated factories. 

```
import javax.annotation.Generated;
import javax.inject.Inject;
@Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
public final class ItemFactory {
  @Inject
  public ItemFactory() {
  }
  public Item create() {
    return new Item();
  }
}
```

@dlemures It's working when factory isn't injected but created manually. 

```
public class MainActivity extends AppCompatActivity {
    
    protected ItemFactory itemFactory = new ItemFactory();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        Scope scope = Toothpick.openScope(this);
        super.onCreate(savedInstanceState);
        Toothpick.inject(this, scope);
    }

    @Override
    protected void onDestroy() {
        Toothpick.closeScope(this);
        super.onDestroy();
    }
}
```

**Comment by dlemures** [comment] 2017-01-20 15:48
Probably related to: https://github.com/stephanenicolas/toothpick/issues/158

**Comment by stephanenicolas** [comment] 2017-05-27 18:15
Yeah, the issue here is that for registries, and for TP in general, we expect only one round of annotations... We need to make sure this is better done in TP2. I will create an issue for this.

**Closed** 2017-05-27 18:16 UTC

**Comment by stephanenicolas** [comment] 2017-07-28 21:44
A simple fix could actually be to add a flag to generate the registries on the last round of annotation processing. It's bad, but expecting a single round of annotation processing is actually worse as it breaks libs like auto factory and auto value.
