### ISSUE TITLE
Override binding problem

### ISSUE THREAD

**Issue by terrakok** [stephanenicolas/toothpick#335] opened 2019-06-12 08:51 UTC
I have AppScope with AppModule who provides pure OkHttpClient via HttpClientProvider.
There is SessionScope with SessionModule as child for AppScope. I need override OkHttpClient for this scope:  
```kotlin
class OkHttpClientProviderWithAuth @Inject constructor(
    private val authData: AuthHolder,
    private val client: OkHttpClient
) : Provider<OkHttpClient> {

    override fun get() = client
        .newBuilder()
        .addNetworkInterceptor(AuthHeaderInterceptor(authData))
        .build()
}
```
I make it inside SessionModule:
```kotlin
bind(OkHttpClient::class.java)
  .toProvider(OkHttpClientProviderWithAuth::class.java)
  .providesSingletonInScope()
```

But take this error:
```
toothpick.configuration.CyclicDependencyException: Class okhttp3.OkHttpClient creates a cycle:
    
                 ==============
                ||            ||
                \/            ||
       okhttp3.OkHttpClient   ||
                ||            ||
       okhttp3.OkHttpClient   ||
                ||            ||
                 ==============
    
        at toothpick.configuration.RuntimeCheckOnConfiguration.checkCyclesStart(RuntimeCheckOnConfiguration.java:63)
        at toothpick.configuration.Configuration.checkCyclesStart(Configuration.java:75)
        at toothpick.ScopeImpl.getInstance(ScopeImpl.java:55)
        at toothpick.ScopeImpl.getInstance(ScopeImpl.java:49)
```

I understood why it happens but I don't know how I can do it correctly.

PS: my workaround is provide root http client with qualifier but it is not conveniently.

**Comment by stephanenicolas** [comment] 2019-06-12 11:10
I don't have a better workaround than yours.

It's not so much a toothpick question than what you do in your app and how
you design it.

**Comment by terrakok** [comment] 2019-06-12 11:17
Why is it not Toothpick question?

If I want to override some binding in child scope then I can do it.

But if this overriding depends on original value (wrap it, for example) then it doesn't work

**Comment by stephanenicolas** [comment] 2019-06-12 12:02
I didn't mean it in a bad way. I just wanted to point that TP is behaving
as intended.

In your provider you are asking to get a okhttpclient, which triggers the
providers..and so you got a cycle.
Possible workarounds are:
* using qualifiers
* creating the instance of the provider manually so that TP doesn't have a
cycle



Le mer. 12 juin 2019 à 07:17, Konstantin <notifications@github.com> a
écrit :

**Comment by terrakok** [comment] 2019-06-12 12:46
> In your provider you are asking to get a okhttpclient, which triggers the
providers..and so you got a cycle.  

Yes, I understand it but I think that more logicaly:
 * I am asking to get `okhttpclient` provider
 * Provider is asking  to get `okhttpclient`
 * Scope handles this situation and asks parent scope  

Because problem is only in trying to get the class that we redefine.

Otherwise, we have to add qualifier to okhttpclient for all classes which creates from parent scope.

Or new workaround:   
1) parent scope have to contains two bindings:

```kotlin
bind(OkHttpClient::class.java)
  .toProvider(PureOkHttpClientProvider::class.java)
  .providesSingletonInScope()

bind(OkHttpClient::class.java)
  .withName(SpecialForDisableCycle::class.java)
  .toProvider(PureOkHttpClientProvider::class.java)
  .providesSingletonInScope()
```

2) OkHttpClientProviderWithAuth have to qualifies okHttpClient:
```kotlin
class OkHttpClientProviderWithAuth @Inject constructor (
  @SpecialForDisableCycle private val okHttpClient: OkHttpClient,
  ...
): ...
```

**Comment by stephanenicolas** [comment] 2019-06-26 16:35
@terrakok , I close the issue. Feel free to re-open if needed, it looks like all is fine on our side.

**Closed by stephanenicolas** 2019-06-26 16:35 UTC
