### ISSUE TITLE
java.lang.NoSuchMethodError on Toothpick.reset() on Instrumentation Tests

### ISSUE THREAD

**Issue by kelsos** [stephanenicolas/toothpick#186] opened 2017-01-06 23:25 UTC
Hi, 

I had an issue while running a couple of instrumentation tests on Android with Toothpick 1.0.3. 
The issue is the following and doesn't appear to happen with v1.0.2:

```
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentH
ashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
        at toothpick.Toothpick.reset(Toothpick.java:125)...
```

This always happens when the tear down method calls the `Toothpick.reset()` method.

**Comment by dlemures** [comment] 2017-01-10 18:10
http://valery-frolov.blogspot.com.es/2015/04/javalangnosuchmethoderror.html

**Comment by efung** [comment] 2017-01-10 20:04
@kelsos Are you compiling with `sourceCompatibility JavaVersion.VERSION_1_8`? We're using Retrolambda and ran into this also.

There's some discussion of this issue in https://code.google.com/p/android/issues/detail?id=215828 as well as in https://gist.github.com/AlainODea/1375759b8720a3f9f094

However, it sounds like in the Android API, the return type of `keySet()` is still `Set<K>`?

**Comment by kelsos** [comment] 2017-01-10 20:08
@efung No the source code and tests are all in kotlin.

**Comment by efung** [comment] 2017-01-10 20:19
Hmm. I don't get it: why is this happening then? Is it because the toothpick artifacts were compiled against Java 1.8? (But I see source compatibility of 1.7 in the project.)

**Comment by kelsos** [comment] 2017-01-10 20:23
@efung when I was searching for the cause I found this discussion http://stackoverflow.com/questions/32954041/concurrenthashmap-crashing-application-compiled-with-jdk-8-but-targeting-jre-7

**Comment by stephanenicolas** [comment] 2017-01-11 15:43
The problem is related to a different implementation in jdk 8 and Android SDK which is based on java 5/7. 

We think we got a workaround

**Comment by efung** [comment] 2017-01-11 16:01
Ah, so is the issue that you compiled the artifacts for Toothpick with JDK 1.8? I'm trying to make sense of [this comment](https://code.google.com/p/android/issues/detail?id=215828#c10) against the `sourceCompatibility` of 1.7 in [Toothpick's `build.gradle`](https://github.com/stephanenicolas/toothpick/blob/master/toothpick/build.gradle#L3)

**Comment by dlemures** [comment] 2017-01-18 21:02
Yes, we are compiling with JDK 1.8.

PR with workaround: https://github.com/stephanenicolas/toothpick/pull/190

**Comment by stephanenicolas** [comment] 2017-01-19 00:02
Just to say that the PR is actually a fix, not a workaround. A workaround
would be to use JDK 8...

2017-01-18 13:02 GMT-08:00 Daniel Molinero <notifications@github.com>:

**Comment by dlemures** [comment] 2017-01-19 01:30
PR merged.

@kelsos Could you update the issue once 1.0.4 is released?

**Comment by kelsos** [comment] 2017-01-19 08:22
@dlemures Yes I will update it after the release.

**Comment by dlemures** [comment] 2017-01-19 12:09
@kelsos I released a snapshot with the changes: 1.0.4-SNAPSHOT

Can you try it?

**Comment by kelsos** [comment] 2017-01-19 13:12
@dlemures I tried the snapshot and it seems to work fine. The error is gone.

**Comment by dlemures** [comment] 2017-01-19 14:25
Awesome. Thx for the help!
Closing

**Closed by dlemures** 2017-01-19 14:25 UTC
Labels: bug, has PR
